version: '3'

volumes:
    postgres_data_dev:

services:

    database:
        image: postgres
        volumes:
            - postgres_data_dev:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5430:5432"
