"""empty message

Revision ID: 49382bac20f0
Revises: 
Create Date: 2018-11-22 13:30:42.989632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49382bac20f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=16), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_account_number'), 'balance', ['account_number'], unique=True)
    op.create_table('ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=16), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('accounting_type', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger')
    op.drop_index(op.f('ix_balance_account_number'), table_name='balance')
    op.drop_table('balance')
    # ### end Alembic commands ###
