"""empty message

Revision ID: be4e8c286845
Revises: 49fbb365a44a
Create Date: 2019-01-23 20:54:40.636112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4e8c286845'
down_revision = '49fbb365a44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ledger', sa.Column('transaction_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ledger', 'transaction_id')
    op.drop_column('ledger', 'created_at')
    # ### end Alembic commands ###
